// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIO8Jf1f7Sd8r7_Svko4GcATpFZpKoK3M',
    appId: '1:18452770682:web:5e1cdc1504e3f2e1b730c3',
    messagingSenderId: '18452770682',
    projectId: 'bookreader-635f1',
    authDomain: 'bookreader-635f1.firebaseapp.com',
    databaseURL: 'https://bookreader-635f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookreader-635f1.appspot.com',
    measurementId: 'G-F0ZYDCJCJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VV_RCkuitGjexA2UrJScYqHwRq4dOcI',
    appId: '1:18452770682:android:f65e368bab0764c1b730c3',
    messagingSenderId: '18452770682',
    projectId: 'bookreader-635f1',
    databaseURL: 'https://bookreader-635f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookreader-635f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQKmhlKCWKCKmBtjYlyEG3bKjwtSL3PKY',
    appId: '1:18452770682:ios:713a86948e8ae4c6b730c3',
    messagingSenderId: '18452770682',
    projectId: 'bookreader-635f1',
    databaseURL: 'https://bookreader-635f1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bookreader-635f1.appspot.com',
    iosClientId: '18452770682-ia6ucgin6t6de8vh2prdjquded4pds1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookReader',
  );
}
